# src: ./configs/codegpt.config.yaml
# @(#) : codeGPT config for model and lang
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# Released under the MIT License.
# https://opensource.org/licenses/MIT

openai:
  provider: "openai"
  model: gpt-4.1-mini

output:
  lang: ja
