# src: ./configs/secretlint.config.yaml
# @(#) : secretlint rules config
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# Released under the MIT License.
# https://opensource.org/licenses/MIT

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
