# src: templates/.markdownlint.yaml
## @(#) : markdown lint settings
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

# markdown lint rule configs
## default rules
default: true
#  white spaces
whitespace: true

##
line-length:
  line_length: 120
  code_block_line_length: 120
ol-prefix: true
emphasis-style:
  style: asterisk
strong-style:
  style: asterisk
no-hard-tabs: true
